--- # Installing Lynx
- hosts: Debian
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing LYNX
    apt: name={{ item }} state=installed update_cache=true
    with_items:
    - lynx
    - telnet
  - name: verify LYNX is installed
    apt: name={{ item }} state=present
    with_items:
    - lynx
    - telnet
 
