--- #LOOPS Playbook
- hosts: all
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Adding users using USER module--example of loops
    user: name={{ item }} state=absent
    with_items:
    - user1
    - user2
