--- #PROMPT Playbook
- hosts: RedHat
  remote_user: test
  connection: ssh
  become: yes
  gather_facts: yes
  vars_prompt:
  - name: pack
    prompt: packages to install
    private: no
    default: telnet
  tasks:
  - name: Install a package
    yum: pkg={{ pack }} state=installed
